bigchaindb/BEPs

1/README.md
Solution: use the ZeroMQ C4 collaboration model.
We can use this PR to fine tune C4 to our needs. Please note that the status of this proposal is **raw**. We should keep it **raw** or **draft** until we are comfortable with it.
=> Problem: there is no collaboration model

2/README.md
Solution: "borrow" ideas from the EIP/BIP/PEP and integrate some other ideas from @muawiakh [specification document](https://github.com/bigchaindb/bigchaindb/blob/0216ffd1e8e173e1e25c2954e207d6976a60dc6/proposals/examples/example-feature-x-spec.md).
=> Problem: there is no template for a spec

1/README.md, 2/README.md, README.md
Solution: switch to BigchainDB Enhancement Proposal, or BEP. Update the index page as well.
Close #4
=>  Problem: RFC is a too generic name

3/README.md, dynamic_validators/insecure_dynamic_validators.md
The spec discuss the challenges and implementation details for dynamically adding validators.
=> Spec to dynamically add/update/remove validators at runtime

1/README.md
=> Problem: Evolution of Public Contracts not linked

3/README.md
Solution: Change to correct BEP type and add copyright waiver declaration.
=> Problem: BEP type incorrect, copyright unspecified

README.md
=> Add 3/UPSERT-VALIDATORS to the table

1/README.md, 2/README.md, README.md
Solution: Change the status from raw to draft.
=> Problem: 1/C4 and 2/COSS are raw but in use

3/README.md, 4/README.md, README.md
:police_car: :police_car: Solution: Fix the typos :police_car: :police_car:
=> Problem: Typos in BEPs and project README

1/README.md
Solution: Define "Public Contracts"
=> Problem: Public Contracts undefined

README.md
:police_car::fire_engine::ambulance:To the rescue again!! :police_car: :fire_engine::ambulance:
=> Fixing typos again

6/README.md, README.md
Solution: have guidelines on how we can work together in a shared space
To the reviewer: It's basically the one I already posted in [bigchaindb/org](https://github.com/bigchaindb/org/pull/37). I've changed the title of the sections to aligne them with 2/COSS, it should make sense.
=> Problem: working in a shared space is difficult

8/README.md, crash-recovery/README.md
Solution: Propose a technique to restore state after a crash has occured.
=> [8/CRASH-RECOVERY] Problem: There is no crash recovery technique.

README.md
8/CRASH-RECOVERY was written by @kansi . It was merged by @codegeschrei today.
=> Add 8/CRASH-RECOVERY to README.md

README.md
Solution: List the C4 roles and who does them, if known
=> Problem: Unclear who does what

README.md
Solution: rearrange sections and put intro first
=> Problem: intro is not the first thing to read

5/README.md
Solution: Make changes to BEP-5 (IDRP) based on recent news and feedback
=> Problem: Recent news & feedback not incorporated in BEP-5 yet

14/README.md, README.md
Solution: write a proposal on how drivers make use of all nodes in the network.
=> Problem: drivers reliability is low

17/README.md, README.md
Solution: Figure out what it would take to get BigchainDB listed on Azure Marketplace and do that. Start with a single node on a single VM.
=> Problem: BigchainDB is not listed in Azure Marketplace (BEP-17)

2/README.md
Solution: include the "Solution Criteria" section into the BEP template
=> Problem: the BEP template does not ask to specify solution criteria

10/README.md
Solution: Be very explicit about BEP-10 goals. Additionaly, be more explicit about choosing Go as a language. Add some minor refinements.
=> Problem: BEP-10 goals are vague.

README.md
=> Problem: BEP-19 isn't in the list of current BEPs

14/README.md
Solution: Refine the algorithm to incorporate timeout and exp backoff. Explicitly describe how common and custom headers are set together.
=> Problem: BEP-14 lacks timeout handling and exp backoff.

18/README.md
Solution: Change < to <=
Note 1: I wasn't able to figure out how to get the LaTeX rendering thing to render ≤
Note 2: This is a follow-up to pull request #60
=> Problem: In BEP-18, the < constraint should be <=

16/README.md, README.md
Solution: Create a new Meta BEP specifying how to handle external PRs
@manolodewiner I put you as the reviewer because you asked me how to handle an external pull request a few weeks ago, and I pointed you to the document in the bigchaindb/bigchaindb repo, but realized it would make more sense for that document to be global to all BigchainDB repositories.
=> Problem: No global doc on how to handle external PRs (BEP-16)

5/README.md
Solution: Give a concrete example of how to modify a SHA-3 hash function in BEP-5
I also condensed the subsection titled **Your Expected Response**.
=> Problem: No example of how to modify hashes in BEP-5

18/README.md, 18/election_transaction.yaml, 18/election_transaction_vote.yaml
- Document schemas.
- Describe basic CLI.
- Add a note on the election threshold.
=> Extend BEP 18
